name: Dart Analyze Code Scanning

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        dir: [ 'owasp-top10-2016-mobile/m2/cool_games/mobile', 'owasp-top10-2016-mobile/m4/note-box/mobile', 'owasp-top10-2016-mobile/m5/panda_zap/mobile' ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.0.2

      - name: Install dependencies
        run: flutter pub get

      - name: Dart Analyze
        run: dart analyze > dart_analyze.txt || true
        
      - name: Debug
        run: |
          pwd
          ls -ls dart_analyze.txt
          cat dart_analyze.txt

      - name: Dart Analyze to SARIF
        uses: advanced-security/dart-analyzer-sarif@main
        with:
          input: "${{matrix.dir}}/dart_analyze.txt"
          output: "${{matrix.dir}}/dart_analyze.sarif"
      
      - name: Name the artifact without "/" 's 
        run: |
          echo "APP_NAME=$(echo ${{matrix.dir}} | rev | cut -d "/" -f 2 | rev)" >> $GITHUB_OUTPUT
        id: appname
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: ${{ steps.appname.outputs.APP_NAME }}
          path: "${{matrix.dir}}/dart_analyze.sarif"
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "${{matrix.dir}}/dart_analyze.sarif"
          # Need unique category since we will be uploading multiple code scanning results in one go
          category: "/app:${{ steps.appname.outputs.APP_NAME }}"
